name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: mxhx-component-haxelib
          path: |
            src/
            haxelib.json
            README.md
            LICENSE
            NOTICE
            CHANGELOG.md
          if-no-files-found: error
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4
      - name: Set up Haxelib dependencies
        run: |
          haxelib install dox --quiet
          haxelib git mxhx-macro-resolver https://github.com/mxhx-dev/mxhx-macro-resolver.git --quiet
          haxelib dev mxhx-component ${{ github.workspace }}
      - name: Build API reference
        working-directory: docs
        run: haxe docs.hxml
      - uses: actions/upload-artifact@v4
        with:
          name: mxhx-component-docs
          path: bin/api/
          if-no-files-found: error
  tests:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cedx/setup-hashlink@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib git mxhx-macro-resolver https://github.com/mxhx-dev/mxhx-macro-resolver.git --quiet
          haxelib dev mxhx-component ${{ github.workspace }}
      - name: Run Interpreter Tests
        working-directory: test
        run: haxe test.hxml --interp
      - name: Run Neko Tests
        working-directory: test
        run: |
          haxe test.hxml --neko bin/test.n
          neko bin/test.n
      - name: Run HashLink Tests
        working-directory: test
        run: |
          haxe test.hxml --hl bin/test.hl
          hl bin/test.hl
      - name: Run Node Tests
        working-directory: test
        run: |
          haxe test.hxml --js bin/test.js
          node bin/test.js
      - name: Run C++ Tests
        working-directory: test
        run: |
          haxe test.hxml --cpp bin/test
          bin/test/Main
